//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutorizationVar4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToyMaterial
    {
        public int idToy { get; set; }
        public int idMaterial { get; set; }
        public int count { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Toy Toy { get; set; }
    }
}
